// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Z_J2qhwfsmTEvvrGho2-4kQwbuWUyBI',
    appId: '1:214353159558:web:a36790c657432fb1c23807',
    messagingSenderId: '214353159558',
    projectId: 'engineering-hub-768ea',
    authDomain: 'engineering-hub-768ea.firebaseapp.com',
    storageBucket: 'engineering-hub-768ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCpIFAL7A0OJN7U3p7CJS7A6hSnXlHDwo',
    appId: '1:214353159558:android:f2d959fac73647c4c23807',
    messagingSenderId: '214353159558',
    projectId: 'engineering-hub-768ea',
    storageBucket: 'engineering-hub-768ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ3o-9EDFEFZ9EM15aEeqJZOGUR0GtqUo',
    appId: '1:214353159558:ios:3af15ba7cdd8c4eec23807',
    messagingSenderId: '214353159558',
    projectId: 'engineering-hub-768ea',
    storageBucket: 'engineering-hub-768ea.appspot.com',
    iosBundleId: 'com.example.engineeringHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ3o-9EDFEFZ9EM15aEeqJZOGUR0GtqUo',
    appId: '1:214353159558:ios:3af15ba7cdd8c4eec23807',
    messagingSenderId: '214353159558',
    projectId: 'engineering-hub-768ea',
    storageBucket: 'engineering-hub-768ea.appspot.com',
    iosBundleId: 'com.example.engineeringHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4Z_J2qhwfsmTEvvrGho2-4kQwbuWUyBI',
    appId: '1:214353159558:web:91d73c2b69852e93c23807',
    messagingSenderId: '214353159558',
    projectId: 'engineering-hub-768ea',
    authDomain: 'engineering-hub-768ea.firebaseapp.com',
    storageBucket: 'engineering-hub-768ea.appspot.com',
  );
}
